"""description du changement

Revision ID: d7195db52b90
Revises: 0001
Create Date: 2026-07-25 22:43:12.922896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7195db52b90'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'airport_local_parameter_values', 'airport_local_parameters', ['parameter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'airport_local_parameters', 'airports', ['airport_key'], ['key'], ondelete='CASCADE')
    op.create_foreign_key(None, 'link_parameter_values', 'link_parameters', ['parameter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'link_parameters', 'network_links', ['link_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_network_items_airport_category', table_name='network_items')
    op.drop_index('uq_network_items_airport_category_title', table_name='network_items')
    op.create_foreign_key(None, 'network_items', 'airports', ['airport_key'], ['key'], ondelete='CASCADE')
    op.drop_index('ix_network_links_lookup', table_name='network_links')
    op.create_foreign_key(None, 'network_links', 'airports', ['from_airport_key'], ['key'], ondelete='CASCADE')
    op.create_foreign_key(None, 'network_links', 'airports', ['to_airport_key'], ['key'], ondelete='CASCADE')
    op.create_foreign_key(None, 'network_sub_parameters', 'network_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('username', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('username', 'users', ['username'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'network_sub_parameters', type_='foreignkey')
    op.drop_constraint(None, 'network_links', type_='foreignkey')
    op.drop_constraint(None, 'network_links', type_='foreignkey')
    op.create_index('ix_network_links_lookup', 'network_links', ['category', 'item_title'], unique=False)
    op.drop_constraint(None, 'network_items', type_='foreignkey')
    op.create_index('uq_network_items_airport_category_title', 'network_items', ['airport_key', 'category', 'title'], unique=True)
    op.create_index('ix_network_items_airport_category', 'network_items', ['airport_key', 'category'], unique=False)
    op.drop_constraint(None, 'link_parameters', type_='foreignkey')
    op.drop_constraint(None, 'link_parameter_values', type_='foreignkey')
    op.drop_constraint(None, 'airport_local_parameters', type_='foreignkey')
    op.drop_constraint(None, 'airport_local_parameter_values', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.alter_column('activity_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
